module.exports.userController = require('./user.controller')
module.exports.zakladController = require('./zaklad.controller')
module.exports.newspaperController = require('./newspaper.controller')
module.exports.commentController = require('./comment.controller')
module.exports.ratingController = require('./rating.controller')
module.exports.refreshTokenController = require('./refresh-token.controller')
